In [ ]:
# All dependencies of this notebook

# third-party imports
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

# local imports
from lib.model import OSDT
from lib.model_selection import train_cross_validate
from lib.data_processing import read_dataset

# Using COMPAS as an example
dataset = read_dataset('data/preprocessed/compas-binary.csv') 
(n, _m) = dataset.shape
X = dataset.values[:,:-1]
y = dataset.values[:,-1]

hyperparameters = {
    'regularizer': 0.005,
    'compress': True
}
model = OSDT(**hyperparameters)
model.fit(X, y)
model.predict(X)

X.values[:, 0]

In [6]:
import numpy as np
import time
# Test out the cluster library
from lib.data_processing import read_dataset
from lib.osdt_definition import OSDT

dataset = read_dataset('data/preprocessed/compas-binary.csv') 
(n, m) = dataset.shape

n = n
X = dataset.values[0:n,0:m-1]
y = dataset.values[0:n,-1]
lamb = 0.005

print((n, m))
print(X)
print(y)

start = time.time()

problem = OSDT(X, y, lamb)
model = problem.solve(clients=1, servers=1)

# y_hat = np.array(list(map(model.predict, (X[i,0:m] for i in range(n)))))
# print('y = {}'.format(''.join(map(str, y))))
# print('y_hat = {}'.format(''.join(map(str, y_hat))))

finish = time.time()
print('runtime = {} seconds'.format(round(finish - start, 3)))

(6907, 13)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 1 0]
 [1 0 1 ... 0 1 0]]
[0 1 1 ... 0 0 1]
Row Compression Factor: 56.154
Negative Gini Reductions: (-0.004387663323232538, -0.0037797971731732827, -0.004810643384345337, -0.00654485726922871, -0.008186064863927589, -0.006974916342042448, -0.008619515986864112, -0.01958141172221689, -0.026124397059193227, -0.0032836372841372197, -0.000444101436871569, -0.03628271947957118)
Negative Gini Reductions Index: (11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10)
Optimal Tree:
(_,_,_,0,_,_,_,_,_,_,_,0) => predict 0, risk contribution 0.12878746199507746
(_,_,_,1,_,_,_,0,_,_,_,0) => predict 1, risk contribution 0.022518459533806285
(_,_,_,1,_,_,_,1,_,_,0,0) => predict 0, risk contribution 0.0708751990734038
(_,_,_,1,_,_,_,1,_,_,1,0) => predict 1, risk contribution 0.022228898219197917
(_,_,_,_,_,_,_,_,_,_,_,1) => predict 1, risk contribution 0.11155856377587954
Optimal Risk: 0.35596858259736497
runtime 

In [ ]:
from lib.similarity_index import SimilarityIndex
import lib.vector as vect
index = SimilarityIndex(3, 1, 2)
a = vect.vectorize([0, 0, 0])
b = vect.vectorize([1, 0, 0])
c = vect.vectorize([0, 1, 0])
d = vect.vectorize([0, 0, 1])
print(a, b, c, d)
print(str(index))
# index.put(a)
index.put(b)
index.put(c)
index.put(d)
print(str(index))
print(index.neighbours(a))