In [1]:
import pandas as pd
import numpy as np
import heapq
import math
import time

import gmpy2
from gmpy2 import mpz
import re

from sklearn import tree

import cProfile

from random import randint, sample, seed

from corels_dt_nosimilar_multicopies import bbound

ModuleNotFoundError: No module named 'corels_dt_nosimilar_multicopies'

In [2]:
# Read in the dataset
# compas1 = pd.DataFrame(pd.read_csv('../data/preprocessed/compas-binary.csv',sep=";"))
# monk1 = pd.DataFrame(pd.read_csv('../data/preprocessed/monk1-train.csv',sep=";"))
# monk2 = pd.DataFrame(pd.read_csv('../data/preprocessed/monk2-train.csv',sep=";"))
# monk3 = pd.DataFrame(pd.read_csv('../data/preprocessed/monk3-train.csv',sep=";"))
# balance = pd.DataFrame(pd.read_csv('../data/preprocessed/balance-scale.csv',sep=";"))
# tictactoe = pd.DataFrame(pd.read_csv('../data/preprocessed/tic-tac-toe.csv',sep=";"))
# car = pd.DataFrame(pd.read_csv('../data/preprocessed/car-evaluation.csv',sep=";"))

compas = pd.DataFrame(pd.read_csv('data/preprocessed/compas-binary.csv',sep=";"))
monk1 = pd.DataFrame(pd.read_csv('data/preprocessed/monk1-train.csv',sep=";"))
monk2 = pd.DataFrame(pd.read_csv('data/preprocessed/monk2-train.csv',sep=";"))
monk3 = pd.DataFrame(pd.read_csv('data/preprocessed/monk3-train.csv',sep=";"))
balance = pd.DataFrame(pd.read_csv('data/preprocessed/balance-scale.csv',sep=";"))
tictactoe = pd.DataFrame(pd.read_csv('data/preprocessed/tic-tac-toe.csv',sep=";"))
car = pd.DataFrame(pd.read_csv('data/preprocessed/car-evaluation.csv',sep=";"))
fico = pd.DataFrame(pd.read_csv('data/preprocessed/fico_binary.csv',sep=";"))


In [9]:
x_monk1 = monk1.values[:,:-1]
y_monk1 = monk1.values[:,-1]

x_monk2 = monk2.values[:,:-1]
y_monk2 = monk2.values[:,-1]

x_monk3 = monk3.values[:,:-1]
y_monk3 = monk3.values[:,-1]

x_compas1 = compas1.values[:,:-1]
y_compas1 = compas1.values[:,-1]

x_balance = balance.values[:,:-1]
y_balance = balance.values[:,-1]

x_tictactoe = tictactoe.values[:,:-1]
y_tictactoe = tictactoe.values[:,-1]

x_car = tictactoe.values[:,:-1]
y_car = tictactoe.values[:,-1]

In [10]:
idxs = [
    [11,7,3,10],
    [11,7,3,10,8], 
    [11,7,3,10,8,6],
    [11,7,3,10,8,6,4],
    [11,7,3,10,8,6,4,5],
    [11,7,3,10,8,6,4,5,2],
    [11,7,3,10,8,6,4,5,2,0],
    [11,7,3,10,8,6,4,5,2,0,1],
    [11,7,3,10,8,6,4,5,2,0,1,9]
]

In [3]:
# How many features can we now reasonably scale to?

df = []

dataset = read_dataset('data/preprocessed/compas-binary.csv')
(n, m) = dataset.shape
X = dataset.values[:,:-1]
y = dataset.values[:,-1]

X = np.copy(x_compas)

sample_size = 4000

row_index = np.random.randint(n, size=sample_size)
X[row_index,:] = np.random.randint(2, size=(n, m))

for j in range(m - 1):
    
    _, _, _, _, nrule, ndata, totaltime, time_c, COUNT, C_c, accu = bbound(
        x_compas, y_compas, lamb=0.005, prior_metric="curiosity", MAXDEPTH=4)
    # compas = compas.append(compas)
    
    x_compas = np.hstack((x_compas,X[:,j].reshape(-1,1)))
    
    print(nrule, ndata, totaltime, time_c, COUNT, C_c, accu)
    df.append([nrule, ndata, totaltime, time_c, COUNT, C_c, accu])
        
df1 = pd.DataFrame(data=np.array(df), columns=["nrule", "ndata", "totaltime", "time_c", "COUNT", "C_c", "accu"])
df1.to_csv('../data/performance_compasbinary_feature.csv',index=False,sep=',')

NameError: name 'read_dataset' is not defined

In [28]:
np.hstack((compas,compas))
aaa = np.array(compas)
aaa[1:3,:] = 
aaa[1:3,:]
#compas

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.hstack((aaa,aaa[:,1:3]))

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 1]])

In [54]:
aaa[:,1]

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [4]:
df = []

for i in range(len(idxs)):
    idx = idxs[i]
    compas = compas1.copy()
    for j in range(2,11):
        x_compas = compas.values[:,:-1]
        y_compas = compas.values[:,-1]
        _, _, _, _, nrule, ndata, totaltime, time_c, COUNT, C_c, accu = bbound(
            x_compas[:,idx], y_compas, lamb=0.005, prior_metric="curiosity", MAXDEPTH=4)
        compas = compas.append(compas1)
        
        df.append([nrule, ndata, totaltime, time_c, COUNT, C_c, accu])
        
df1 = pd.DataFrame(data=np.array(df), columns=["nrule", "ndata", "totaltime", "time_c", "COUNT", "C_c", "accu"])
df1.to_csv('data/performance_compasbinary0.csv',index=False,sep=',')

NameError: name 'idxs' is not defined

In [6]:
df = []

compas = compas1.copy()
for j in range(12):
    x_compas = compas.values[:,:-1]
    y_compas = compas.values[:,-1]
    _, _, _, _, nrule, ndata, totaltime, time_c, COUNT, C_c, accu = bbound(
        x_compas, y_compas, lamb=0.005, prior_metric="curiosity", MAXDEPTH=4)
    compas = compas.append(compas)
    
    print(nrule, ndata, totaltime, time_c, COUNT, C_c, accu)
    df.append([nrule, ndata, totaltime, time_c, COUNT, C_c, accu])
        
df1 = pd.DataFrame(data=np.array(df), columns=["nrule", "ndata", "totaltime", "time_c", "COUNT", "C_c", "accu"])
df1.to_csv('data/performance_compasbinary_new.csv',index=False,sep=',')

nrule: 12
ndata: 6907
gr: [0.00438766 0.0037798  0.00481064 0.00654486 0.00818606 0.00697492
 0.00861952 0.01958141 0.0261244  0.00328364 0.0004441  0.03628272]
order: [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10]
odr: [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10]
the order of x's columns:  [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10]
>>> log: False
>>> support bound: True
>>> incre_support: True
>>> accurate support bound: True
>>> equiv points bound: True
>>> lookahead bound: True
prior_metric= curiosity
total time:  8.0111563205719
lambda:  0.005
leaves:  [(1,), (-7, -1), (-1, 7, 12), (-12, -3, -1, 7), (-12, -1, 3, 7)]
num_captured:  [2174, 2898, 483, 205, 1147]
num_captured_incorrect:  [736, 855, 164, 76, 455]
prediction:  [1, 0, 1, 1, 0]
Objective:  0.35596858259736497
Accuracy:  0.669031417402635
COUNT of the best tree:  6474
time when the best tree is achieved:  0.4586622714996338
TOTAL COUNT:  201981
12 6907 8.0111563205719 0.4586622714996338 201981 6474 0.669031417402635
nrule: 12
ndata: 13814
gr

>>> log: False
>>> support bound: True
>>> incre_support: True
>>> accurate support bound: True
>>> equiv points bound: True
>>> lookahead bound: True
prior_metric= curiosity
total time:  42.25383496284485
lambda:  0.005
leaves:  [(1,), (-7, -1), (-1, 7, 12), (-12, -3, -1, 7), (-12, -1, 3, 7)]
num_captured:  [556544, 741888, 123648, 52480, 293632]
num_captured_incorrect:  [188416, 218880, 41984, 19456, 116480]
prediction:  [1, 0, 1, 1, 0]
Objective:  0.35596858259736497
Accuracy:  0.669031417402635
COUNT of the best tree:  6474
time when the best tree is achieved:  27.3837730884552
TOTAL COUNT:  201981
12 1768192 42.25383496284485 27.3837730884552 201981 6474 0.669031417402635
nrule: 12
ndata: 3536384
gr: [0.00438766 0.0037798  0.00481064 0.00654486 0.00818606 0.00697492
 0.00861952 0.01958141 0.0261244  0.00328364 0.0004441  0.03628272]
order: [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10]
odr: [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9, 10]
the order of x's columns:  [11, 8, 7, 6, 4, 5, 3, 2, 0, 1, 9

sex:Female  age:<21  age:<23  age:<26  age:<46  juvenile-felonies:=0  \
0              0        0        0        0        0                    10   
1              0        0        0        0       10                    10   
2              0        0       10       10       10                    10   
3              0        0        0        0       10                    10   
4              0        0        0        0       10                    10   
5              0        0        0        0       10                    10   
6             10        0        0        0       10                    10   
7              0        0       10       10       10                    10   
8              0        0        0        0       10                    10   
9              0        0       10       10       10                    10   
10            10        0        0        0       10                    10   
11             0        0        0        0       10                    10   
12            10        0        0        0        0                    10   
13             0        0        0        0       10                    10   
14             0        0        0        0       10                    10   
15             0        0        0       10       10                    10   
16             0        0        0        0       10                    10   
17             0        0        0        0       10                    10   
18             0        0        0        0        0                    10   
19             0       10       10       10       10                    10   
20             0        0        0        0       10                    10   
21            10       10       10       10       10                    10   
22             0        0       10       10       10                    10   
23             0        0        0        0       10                    10   
24             0        0        0        0       10                    10   
25             0        0        0       10       10                    10   
26            10        0        0        0       10                    10   
27             0        0        0       10       10                    10   
28             0        0        0        0       10                    10   
29             0        0        0        0       10                    10   
...          ...      ...      ...      ...      ...                   ...   
6877          10        0        0        0       10                    10   
6878           0        0        0        0       10                    10   
6879           0        0        0        0       10                    10   
6880           0        0        0        0        0                    10   
6881           0        0        0        0       10                    10   
6882           0        0        0        0       10                    10   
6883           0        0       10       10       10                    10   
6884           0        0        0        0        0                    10   
6885           0        0        0        0       10                    10   
6886           0        0        0       10       10                    10   
6887          10        0        0        0       10                    10   
6888           0        0        0        0       10                    10   
6889           0        0        0        0       10                    10   
6890           0        0        0        0       10                    10   
6891           0        0        0        0       10                    10   
6892           0        0       10       10       10                    10   
6893          10       10       10       10       10                    10   
6894           0        0        0        0       10                    10   
6895           0        0        0       10       10                    10   
6896           0        0   